### ISSUE TITLE
[suggestion] add semilog y-axis plots

### ISSUE THREAD

**Issue by stevenqzhang** [xunhuang/covid-19#1]
A suggestion- if you add semilog-y plots, that might be very helpful

For example, see https://www.ft.com/content/a26fbf7e-48f8-11ea-aeb3-955839e06441

**Comment by xunhuang** [comment]
great suggestion. I'll add it to my list. I tried to do that one point, but it did't work. I'm using the ReChart.org's widget. If you can tell me how to add it, I will do it right the way.

**Comment by stevenqzhang** [comment]
I think this would probably help: https://github.com/recharts/recharts/issues/575

Sorry I don't have much experience with JS-based plotting/charting, I've been using Tableau for years. Also I did a mini-writeup that you might find helpful for framing: https://docs.google.com/document/d/17YnG3RBeHqJSYT3YE1PzcfXb2E6YuAhrObmoVOKFwbY/edit#

**Comment by xunhuang** [comment]
this is helpful. let me try that.

**Comment by xunhuang** [comment]
https://imgur.com/a/iiX8RkW it works. now I need to figure out how to add a button in the chart to change it.

**Comment by stevenqzhang** [comment]
Awesome! One useful thing about semilog plots is ability to compare slopes- potentially think about adding a compare regions feature down the road?

**Comment by xunhuang** [comment]
just added the log scale. Thanks for the suggestion
