### ISSUE TITLE
Santa Clara County (and others) Daily Data Disappeared

### ISSUE THREAD

**Issue by dnola** [xunhuang/covid-19#140]
Hello,

The tab containing # of cases per day for many counties, such as Santa Clara county, has disappeared. Is this intentional?

I really liked that feature personally! Curious about its disappearance. Thank you for your time and work!

**Comment by xunhuang** [comment]
hi, is this what you are looking for? 

![image](https://user-images.githubusercontent.com/729879/85964171-77c20800-b96d-11ea-917a-8be9931a7193.png)

Or are you referring to the previous "Daily" chart? I removed it because I thought no one is using it. lol.

**Comment by xunhuang** [comment]
this is the one that I disabled (and can be brought back easiy)

![image](https://user-images.githubusercontent.com/729879/85964264-d4252780-b96d-11ea-9b44-1f8c31607ad1.png)

this is largely duplicative with the previous one.

**Comment by dnola** [comment]
Is there a way on the main graph to hide the total # confirmed and auto scale around just the daily data?

I liked the simpler looking graph for easy to read screencaps, but can understand that behavior is largely redundant from a functional standpoint.

This looks like plot.ly Dash - there was an option to make the series hideable IIRC - maybe that would do it?

**Comment by xunhuang** [comment]
sorry, didn't see the comment until today. You can click on the label to enable/disable the data series. 
for instance, the Confirmed (total) is disabled here. 
![image](https://user-images.githubusercontent.com/729879/87278681-eb99ff80-c499-11ea-91ec-6e795ca70a5a.png)
