### ISSUE TITLE
[suggestion] more sophisticated hospital capacity visualization/calculation

### ISSUE THREAD

**Issue by stevenqzhang** [xunhuang/covid-19#2]
Perhaps we can use your hospital capacity metric to educate viewers about the lag time problem. 

https://tim.blog/2020/03/17/predicting-hospital-capacity-why-to-act-early-how-to-think-about-lag-time-and-a-model-you-can-use/

(my personal opinion here https://docs.google.com/document/d/17YnG3RBeHqJSYT3YE1PzcfXb2E6YuAhrObmoVOKFwbY/edit#heading=h.j88lrw3toi85)

**Comment by xunhuang** [comment]
we have hospitalization capacity graph now with the NPR projection
