### ISSUE TITLE
Add a reference line to the new cases graph

### ISSUE THREAD

**Issue by xunhuang** [xunhuang/covid-19#26]
so I can add "shelter-in-place" line to the new cases graph. 

make it a property so that I pass in 

1) date for the reference line
2) text label  for the reference line

**Comment by xunhuang** [comment]
Yiming, since you are touch the same graph widget, can you please add this ref line? 

I am working on actually getting the shelter in place dates.

**Comment by lym953** [comment]
Done in pull request #27
