### ISSUE TITLE
Add a link to this github repo to main site?

### ISSUE THREAD

**Issue by stevenqzhang** [xunhuang/covid-19#3]
MAybe it's intentionally anonymous, but consider putting a link to this github repo on the site so people know where to file issues, etc.?

**Comment by xunhuang** [comment]
No, not intentionally trying to be anonymous at all, I won't publish the git hub. I will add it to my to do list. I did add a discussion thing on the bottom, so non-tech people can join the discussion.

I haven't forgotten about the log thing. Bear with me, single person working on this.

**Comment by stevenqzhang** [comment]
Got it. thanks for your work!

**Comment by tumbleshack** [comment]
@xunhuang 

If you don't mind, I can add this to the header and make a PR? Looking to improve my React :)

I love your work here!

**Comment by xunhuang** [comment]
happy to have this added. do you have a specific place in mind? (as header is kind of crowded.) Maybe create a footer? things I think would benefit from the footers are 

1) Link to Github + FB working group
2) Term of service (disclaimer on data)
3) FAQ
4) Data Credits
5) Credits for people that contributed to this project
6) Data download links.

**Comment by tumbleshack** [comment]
I can definitely try my hand at this. I imagine the footer can go below Disqus?

It's a bit odd that Disqus adds their own footer-like area. I'm thinking that if the main site footer goes below Disqus, then maybe the site footer can have a non-white background to distinguish it. Curious if you have any thoughts.

> happy to have this added. do you have a specific place in mind? (as header is kind of crowded.) Maybe create a footer? things I think would benefit from the footers are
> 
> 1. Link to Github + FB working group
> 2. Term of service (disclaimer on data)
> 3. FAQ
> 4. Data Credits
> 5. Credits for people that contributed to this project
> 6. Data download links.

**Comment by aschleck** [comment]
What if we put the Disqus widget in a paper element and then max heighted it with scrollable overflow? Not sure if it would end up looking weird, but at least all the important things in the Disqus widget are at the top

**Comment by xunhuang** [comment]
Let’s try it. Also in exploring whether to make this section with FB
comments. Disqus is trying to charge us $85 a month, and it’s not very
good. So want to experiment with other things.

**Comment by tumbleshack** [comment]
Sounds good. I'll make it a scrollable paper element

**Comment by tumbleshack** [comment]
Here's what it looks like at the moment. Thinking of adding FB icon next to GitHub one. Thoughts on design? 

![image](https://user-images.githubusercontent.com/43155606/80324360-8de10a00-87fe-11ea-9603-21ad7a695e62.png)

Also, where can I find the appropriate links? And what should the credit text be?

**Comment by xunhuang** [comment]
Design looks great. We can refine them later.
For the credit, we can say something generic like 
"This website is is 100% volunteer developed, open source and funded by user donations. Click here for volunteers that made significant contributions." (exact text can be word-smithed better) 
Then we can make a popup to list the names.

**Comment by xunhuang** [comment]
Here is link to the terms of service a lawyer friend help draft

https://docs.google.com/document/d/10bsmpX1VVi2myFAHtP_gqHeGauDHz_9t1YQnjxMc_ng/edit?usp=sharing

**Comment by xunhuang** [comment]
Credit list is here. we should pull this list in recurrently. 

https://docs.google.com/spreadsheets/d/1n4Qr3UkGT_PTNQ6f-HBLWrvXcAZfaotbBTTNzz1juLk/edit?usp=sharing

**Comment by xunhuang** [comment]
Data credit list is built in.

**Comment by tumbleshack** [comment]
Cool. I'll add those now. What do you mean by the data credit list is built-in?

**Comment by tumbleshack** [comment]
Also curious about FAQ & Data Download; once those links are ready, I can publish the PR
