### ISSUE TITLE
Add "new death" curve

### ISSUE THREAD

**Issue by lym953** [xunhuang/covid-19#30]

**Comment by xunhuang** [comment]
I actually want to have a "Life and death" curve.. showing recovery + death on the same curve, maybe with active too.

**Comment by xunhuang** [comment]
hey, can you start working on this? I found the Recovery data from JHU at the national level. Can you start work on a chart while mocking the Recovery data while I extract the data set? I think it will be interesting for people to see it.  Here is what I suggest:
 
1) show it as a new tab, for only the US page Between "Cases" & "Testing"
2) two lines, one for death, and one for life. Death data is in   AllData.Summary.Deaths
3) Recovery data is in AllData.Summary.Recovered.  These are currently empty. Put some mock values there for now. 

I will work out the data extraction and make sure they are populated. thank you!

**Comment by xunhuang** [comment]
manually extracted:
  {
    "Province/State": "",
    "Country/Region": "US",
    "Lat": "37.0902",
    "Long": "-95.7129",
    "1/22/20": "0",
    "1/23/20": "0",
    "1/24/20": "0",
    "1/25/20": "0",
    "1/26/20": "0",
    "1/27/20": "0",
    "1/28/20": "0",
    "1/29/20": "0",
    "1/30/20": "0",
    "1/31/20": "0",
    "2/1/20": "0",
    "2/2/20": "0",
    "2/3/20": "0",
    "2/4/20": "0",
    "2/5/20": "0",
    "2/6/20": "0",
    "2/7/20": "0",
    "2/8/20": "0",
    "2/9/20": "3",
    "2/10/20": "3",
    "2/11/20": "3",
    "2/12/20": "3",
    "2/13/20": "3",
    "2/14/20": "3",
    "2/15/20": "3",
    "2/16/20": "3",
    "2/17/20": "3",
    "2/18/20": "3",
    "2/19/20": "3",
    "2/20/20": "3",
    "2/21/20": "5",
    "2/22/20": "5",
    "2/23/20": "5",
    "2/24/20": "5",
    "2/25/20": "6",
    "2/26/20": "6",
    "2/27/20": "6",
    "2/28/20": "7",
    "2/29/20": "7",
    "3/1/20": "7",
    "3/2/20": "7",
    "3/3/20": "7",
    "3/4/20": "7",
    "3/5/20": "7",
    "3/6/20": "7",
    "3/7/20": "7",
    "3/8/20": "7",
    "3/9/20": "7",
    "3/10/20": "8",
    "3/11/20": "8",
    "3/12/20": "12",
    "3/13/20": "12",
    "3/14/20": "12",
    "3/15/20": "12",
    "3/16/20": "17",
    "3/17/20": "17",
    "3/18/20": "105",
    "3/19/20": "121",
    "3/20/20": "147",
    "3/21/20": "176",
    "3/22/20": "178",
    "3/23/20": "178",
    "3/24/20": "348",
    "3/25/20": "361",
    "3/26/20": "681",
    "3/27/20": "869",
    "3/28/20": "1072",
    "3/29/20": "2665",
    "3/30/20": "5644"
  },
Will automate extraction tomorrow.

**Comment by xunhuang** [comment]
data is available now at AllData.Summary.Recovered

**Comment by xunhuang** [comment]
added
