### ISSUE TITLE
[SEO] Make this website more searchable

### ISSUE THREAD

**Issue by lym953** [xunhuang/covid-19#34]
I think one of the biggest values of this website is county-level data curves. However this site doesn't show up in the Google search result of "covid 19 county level data curve". None of the top results provide what we want. Maybe we can add these words to the title or the page to make it more discoverable.

TODO:

Done:
- Make page titles more informative, e.g. "COVID-19 daily data for Santa Clara, CA" (#38)
- Improve page description ([commit](https://github.com/xunhuang/covid-19/commit/57932eaf2790d7bda70b5197e1cdb6d0516715de))
- Make page description different for every page ([commit](https://github.com/xunhuang/covid-19/commit/6722c7bc26d932d9d7a6693b6d677a327750cc0b))
- Add a basic sitemap containing page urls ([commit](https://github.com/xunhuang/covid-19/commit/ba89033c476df3c0c27b2efcbbe14336113afd28))
  - and submit it to Google Search Console for Google to crawl the pages
- Add 404 page (partially done, see below)
  - 404 page can be shown for some invalid urls, such as:
    - invalid first part: `/USD`
    - invalid state for state page: `/state/NYU`
  - but some invalid urls still lead to an empty page (due to internal error)
    - invalid url for county page: `/county/NY/New` or `/county/NYU/New%20York`

Resource:
[Search Engine Optimization (SEO) Starter Guide](https://support.google.com/webmasters/answer/7451184?hl=en) by Google

**Comment by xunhuang** [comment]
I know nothing about SEO. Love it if you can help figure it out.

**Comment by lym953** [comment]
@xunhuang Seems Google is smart enough. Try searching for "[site:covid-19.direct](https://www.google.com/search?client=safari&rls=en&q=site:covid-19.direct&ie=UTF-8&oe=UTF-8)" on Google.
<img width="605" alt="image" src="https://user-images.githubusercontent.com/10097700/78083901-b09d1180-736b-11ea-8fb5-fd648a7ba09c.png">

**Comment by xunhuang** [comment]
omg! what the heck do i know! even the double every 3.7 days works.

**Comment by xunhuang** [comment]
traffic current at rate of 80K of DAU not sure how long it will last. Let's see if the increased traffic is from google.

**Comment by xunhuang** [comment]
this is our based line 

(direct) 265K
m.facebook.com26K
google 3.1K
facebook.com 2K
t.co 1.2K
l.facebook.com 990

**Comment by lym953** [comment]
> this is our based line

(direct) 265K
m.facebook.com26K
google 3.1K
facebook.com 2K
t.co 1.2K
l.facebook.com 990

This is 120-day data for acquiring new users. Do you think this is a good indicator of growth?

**Comment by lym953** [comment]
Closing this issue. My work done is summarized in the issue description.

Next step:
Wait for several days/weeks for
- Google to crawl the pages
- Google Search Console to collect search performance data

then see if there's anything we can do about it.
