### ISSUE TITLE
Add States Testing table 

### ISSUE THREAD

**Issue by xunhuang** [xunhuang/covid-19#36]
The Testing graph is difficult to read. Let's add a table. Let's make a new tab under the US Page, next to the "States of USA". 

you can read the testing graphs to see where the data is coming from, should be self-explanatory.  I suggest we get the following columns to start with 

States,  Positivie# ,postive rate, negative#, negative rate,  pending, total

You can model that code after the county/state tables with sorting by the columns.

**Comment by lym953** [comment]
Now I have three things in hand:
1. #34 SEO, which I think is most impactful and fun. Our DAU curve has been flat for the past week and I think our site has potential for growth.
2. #30 Add recovery curve.
3. This issue #36, which I think has lowest-pri.

I will work on 1 and 2 first.

**Comment by xunhuang** [comment]
Make sense! Thank you Yiming. I would love to learn how to do this SEO thing. As I understood it's challenging for react apps. let's see if you change worked.
