### ISSUE TITLE
Group counties together, eg. "Bay Area"

### ISSUE THREAD

**Issue by ortutay** [xunhuang/covid-19#5]
It would be useful to view regions like Bay Area the LA metro area as a single unit. I tried poking around the code but couldn't get it to run, but if you can add it quickly it would be neat. Thanks for making the site.

**Comment by xunhuang** [comment]
I can give read access to the firebase site. send me your email.

**Comment by ortutay** [comment]
Thanks, I'll try to add it. my email is marcell.ortutay@gmail.com, I got
referred to your site through a friend-of-a-friend. I've done some react
coding before and developed a site on firebase recently.

**Comment by xunhuang** [comment]
very cool. I only know very basis react stuff so it shouldn't be too hard.

**Comment by xunhuang** [comment]
just add you. I think you will have to do firebase login, then init.

**Comment by xunhuang** [comment]
feel free to hard code the bay area/LA  counties. we can generalize to metros for other cities later.

**Comment by ortutay** [comment]
Can you double check? It says I don't have access:

```
marcell ~/projects/covid-19/website (master) $ firebase login
Already logged in as marcell.ortutay@gmail.com
marcell ~/projects/covid-19/website (master) $ firebase init
# ... snip ...
i  .firebaserc already has a default project, using covid-19-live.

Error: Failed to get Firebase project covid-19-live. Please make sure the
project exists and your account has permission to access it.
```

I can try to set up a separate firebase project though it may be tricky to
get all the configs correct. For `init` step, I'm selecting `Database:
Deploy Firebase Realtime Database Rules` feature only.

**Comment by xunhuang** [comment]
Maybe I shouldn't have checkin the .firebaserc file, can you please try to
remove that and rerun?

I don't suggest you setup another firebase project (even though it's
cleaner from my perspective). you will have to setup geoapi etc etc, too
many things can go wrong.

**Comment by ortutay** [comment]
Yea figured the config would be tricky.

I removed the .firebaserc file, but it then asks me to use one of my
existing projects as the firebase project (see pastebin:
https://pastebin.com/pLdqJHU5). The `covid-19-live` does not show up there,
so most likely I don't have access. I checked my email and don't see
anything from firebase recently.

**Comment by xunhuang** [comment]
I thought I sent you an invite to the firebase project. I think you have to
accept. then the list would show up.

**Comment by ortutay** [comment]
Can you double check? Didn't seem to go through AFAICT..

**Comment by xunhuang** [comment]
[image: image.png]

**Comment by xunhuang** [comment]
I resent again.

**Comment by ortutay** [comment]
Weird...for some reason it's not showing up in me email or firebase console
(marcell.ortutay@gmail.com). possibly a firebase issue, I'll check again
this evening
