### ISSUE TITLE
Add a donation button

### ISSUE THREAD

**Issue by ShuoShen** [xunhuang/covid-19#7]

**Comment by ShuoShen** [comment]
Hey @xunhuang, setting up the project here. Can you please add my account to firebase? It's shuoshen178@gmail.com. Thank you.

**Comment by xunhuang** [comment]
added

**Comment by ShuoShen** [comment]
Thank you!

Do we have % of users on desktop web vs msite? If most traffics are from msite, I can prioritize Apple Pay and Android Pay.

**Comment by xunhuang** [comment]
Maybe you can go to firebase to dig around. I remember seeing more details before but I can't find it 
![image](https://user-images.githubusercontent.com/729879/77719320-3f8fdf80-6fa2-11ea-838e-357fb4374168.png)

that said, i was so thinking about a Direct payment thing but more like a donation button that leads to Paypal or gofundme or a facebook fundraiser type places. That said I know very little this type of things.

**Comment by ShuoShen** [comment]
You were *not* thinking about direct payment?

**Comment by xunhuang** [comment]
pros/cons?

**Comment by ShuoShen** [comment]
3rd party fundraiser is easier to build, but properly lower conversion.

**Comment by xunhuang** [comment]
I'll say let's stay simple first, and measure the conversion. we can do
more work if it doesn't convert

**Comment by xunhuang** [comment]
hey shuo, finally got around to this. (motivated by an actual large bill from google)

ko-fi.com/covid19direct

Can you please update the code to put a small Red button on the top right corner of the site? 
Thanks!

**Comment by ShuoShen** [comment]
Hey, are you visioning a button on the right of the first row? Sounds like
more or less trivial. Feel free to go ahead and put it there.

I can help work on improving conversion if needed.

**Comment by xunhuang** [comment]
added. done.
