### ISSUE TITLE
Add Date-slider to graphs

### ISSUE THREAD

**Issue by xunhuang** [xunhuang/covid-19#86]
currently some graph has a 2-weeks toggle, would be great to have a control that can slide between how many days to show 

---------O---------

Min is the first day of data availability
default is 30
max is 14

not show the control if less than 14 days of data.

**Comment by tumbleshack** [comment]
Slider added, but the "not show if less than 14 days of data" feature is implemented.

**Comment by xunhuang** [comment]
thank you!
