### ISSUE TITLE
Add date slider to show historic views

### ISSUE THREAD

**Issue by xunhuang** [xunhuang/covid-19#97]
from disqus: 
Is it possible to add - or can you point me to a source where it is accessible - a "historical" view for the "States of USA" table on the US/detailed page? Specifically, I'd like to be able to roll that table back to a specific date, to see the doubling rates for the states as of one week ago, two weeks ago, etc.

Interesting feature request!  Are you sure you want to see them in tabular format? I think it might be interesting to do this do this on a map, where you can slide the dates back and forth and see color changes, then you can mouse over to see the numbers.

**Comment by option8** [comment]
I'm looking for tabular data myself, so I can set a date and see all the numbers at once (and sort the table, etc). Being able to view a map over time would be an interesting way of interacting with the data, though.

**Comment by xunhuang** [comment]
if we give you the data (case #) in a tablular format, will you be able to calculate the numbers yourself? 

for instance the attachment. Our methodology is just computing the growth rate/doubling time last 7 data points of any given date. 

[states.txt](https://github.com/xunhuang/covid-19/files/4565749/states.txt)

**Comment by option8** [comment]
Possibly, but I don't know the maths :)

**Comment by xunhuang** [comment]
ok, I will think about this (you think I know math?). :)

**Comment by tumbleshack** [comment]
See #114 and #104

**Comment by xunhuang** [comment]
thank you @tumbleshack for making this happen!
